"""fix notification_type rename

Revision ID: 3be13befa107
Revises: 6b47058dab55
Create Date: 2026-06-20 02:14:50.555498
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3be13befa107'
down_revision: Union[str, None] = '6b47058dab55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_notifications_notification_type'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_todo_id'), table_name='user_notifications')
    op.drop_index(op.f('ix_user_notifications_user_id'), table_name='user_notifications')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_user_notifications_user_id'), 'user_notifications', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_todo_id'), 'user_notifications', ['todo_id'], unique=False)
    op.create_index(op.f('ix_user_notifications_notification_type'), 'user_notifications', ['notification_type'], unique=False)
    # ### end Alembic commands ###
