"""add notification type

Revision ID: 8b90a77be6a3
Revises: c6d7ba2e798b
Create Date: 2026-06-18 18:11:04.559994
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '8b90a77be6a3'
down_revision: Union[str, None] = 'c6d7ba2e798b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_notifications', sa.Column('type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_notifications', 'type')
    # ### end Alembic commands ###
