"""add reminder_sent to todos

Revision ID: c6d7ba2e798b
Revises: a8d278f863e5
Create Date: 2026-06-18 17:16:48.089072
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c6d7ba2e798b'
down_revision: Union[str, None] = 'a8d278f863e5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('reminder_sent', sa.Boolean(), nullable=False,server_default="false"))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'reminder_sent')
    # ### end Alembic commands ###
